### PR TITLE
[#40] Constrain requirements according to what breaks. 

### LINKED ISSUE #40: setup.py incompatible with CKAN deps
Current CKAN master specifies sqlalchemy 1.1.11, so we get an error when installing this and then CKAN's requirements.txt:
```
ckanserviceprovider 0.0.7 has requirement SQLAlchemy<1.3.0,>=1.2.7, but you'll have sqlalchemy 1.1.11 which is incompatible.
```

This is occurred since this PR was merged: https://github.com/ckan/ckan-service-provider/pull/39

### PR DESCRIPTION
**Pull request by davidread**
Fixes #40 

(Pinning is done in requirements.txt if you have trouble reproducing a working environment)

* Undoes the problems of https://github.com/ckan/ckan-service-provider/pull/39
* But I believe fixes https://github.com/ckan/ckan-service-provider/issues/38

### CODE REVIEW

**Comment by gerbyzation** [comment]
I disagree with unpinning versions until they break, in my opinion requirements should be deterministic to allow for reliable builds, instead of being left at the mercy of external dependencies to make no breaking api changes, which is exactly what went wrong with #38. 

I'm not entirely clear on how the setup.py and requirements.txt play together though, if I can remember correctly the requirements.txt file doesn't come to play if ckan-service-provider is installed as a dependency?

**Comment by davidread** [comment]
Do check the links for the reasoning for libraries such as this is.

**Comment by davidread** [comment]
@gerbyzation Sorry for being terse earlier.

Of course it's good practice to pin deps. However these decisions are are always a trade off and habitually datapusher is installed in the same virtualenv as ckan. If we need to diverge in versions of dependencies then we should specify this separation in the datapusher install readme. So whilst you may have done a separated install, the installs of datapusher I've seen aren't, and this PR will cause many developers CKAN upgrade headaches, as I have encountered.

If a python module pins a dependency in setup.py's `install_requires` then you simply can't install any python module with a conflicting setup.py's install_requires - pip won't let you. This is a rigid approach, forcing developers of different CKAN extensions to agree on dep versions and when they all agree to upgrade a dependency, users to upgrade all extensions together in lock-step too. If users want to deviate from this path they hack their setup.py and therefore either fork the codebase for themselves or try to remember not to check in the change.

So we decided for CKAN extensions to simply do the pinning in requirements.txt, which the user applies as a separate step. Whilst it's not great to add another command, it solves the dependency conflict problem. Where there are dependency conflicts the user can simply install a compromise dependency version with `pip install X==Y`. Or a user could maintain a requirements.txt for all their ckan extensions and be deterministic.

Whilst there are no doubt variants on this solution, having a loose setup.py's install_requires seems the norm in python libraries (e.g. [requests](https://github.com/requests/requests/blob/master/setup.py#L50), [flask](https://github.com/pallets/flask/blob/master/setup.py#L36), [scikit-learn](https://github.com/scikit-learn/scikit-learn/blob/master/setup.py#L199)).
I'm very happy to learn more about this if there are better ways to solve this problem.

**Comment by amercader** [comment]
For the record, I always install DataPusher in its own virtualenv just to avoid issues like this. The package install does the same and also the [DataPusher install instructions](http://docs.ckan.org/projects/datapusher/en/latest/deployment.html)) tell you to do so. I agree this should be made more explicitl in the README. I think that given its architecture it makes sense for the DataPusher to live in its own virtualenv, and if that is the case, pinning dependencies makes sense to get a reproducible environment.
Also ckan-service-provider is generally installed as a [requirement of datapusher](https://github.com/ckan/datapusher/blob/master/requirements.txt#L2) via pip so it's difficult to rely on requirements.txt if there are problems.
@davidread do you think adding support for installing it in the same venv as CKAN is worth it?

**Comment by davidread** [comment]
Good to know that @amercader - thanks for point those things out. That changes a lot in my mind and I'm now happy to accept #39 instead of this.

**Pull request closed without merging**
