### PR TITLE
pin dependency versions in setup.py

### LINKED ISSUE #38: dependencies broken because of no version pinning
the flask-login requirement is unpinned in `setup.py`, and from 0.4.0 onward the import has changed from ` flask.ext.login` to `flask_login`, causing an exception.

### PR DESCRIPTION
**Pull request by gerbyzation**
fixes #38

### CODE REVIEW

**Comment by gerbyzation** [comment]
Why do you prefer that? It solves this particular issue, but still leaves the risk of breaking the app in a similar fashion in the future. The purpose of version pinning is to freeze dependencies and give repeatable and reproducible deployments.

**Comment by s-chand** [comment]
@gerbyzation I actually meant in addition. Sorry I phrased it wrongly.

**Comment by amercader** [comment]
Thanks @gerbyzation

@s-chand I think it's safer to explicitly rely on the pinned versions

**Comment by s-chand** [comment]
@amercader of course. Thanks for looking into this.

**Comment by davidread** [comment]
I disagree with this. CKAN ecosystem has long used requirements.txt for pinning, not setup.py's install_requires. This will be biting people now, if not as soon as CKAN changes it's requests or flask version, say.

The reasoning is here: https://github.com/ga4gh/ga4gh-server/issues/1006#issuecomment-200474462
The official python version is here: https://packaging.python.org/discussions/install-requires-vs-requirements/

Sure, specify Flask<1.0 in setup.py since there is a specific incompatibility. (Or even better, fix the incompatibility). However by pinning every dep to a minor release in setup.py causes compatibility with different versions of CKAN.

**Comment by davidread** [comment]
Current CKAN master specifies sqlalchemy 1.1.11, so by this little library not installing unless it is <1.3.0,>=1.2.7, even though it works fine with a range of versions, makes no sense.

```
ckanserviceprovider 0.0.7 has requirement SQLAlchemy<1.3.0,>=1.2.7, but you'll have sqlalchemy 1.1.11 which is incompatible.
```

**Comment by davidread** [comment]
I've changed my mind on this - I'm happy now that I've learnt datapusher (and this) should be installed in a separate virtualenv in CKAN (as discussed in #40).

Sorry for the disruption and for doubting you @gerbyzation & @amercader.

**Comment by amercader** [comment]
Please disrupt away @davidread, that's why we are here :)

**Pull request merged**
